name: 'RandomEvent'
version: '1.0.0'
main: 'me.abhigya.randomevent.RandomEvent'
api-version: 1.18
softdepend:
  - 'packetevents'
  - 'libdisguise'
commands:
  'setarena':
    permission: 'randomevent.command'
  'setsubmit':
    permission: 'randomevent.command'
  'settnt':
    permission: 'randomevent.command'
  'setparkour':
    permission: 'randomevent.command'
  'settrap':
    permission: 'randomevent.command'
  'eventdebug':
    permission: 'randomevent.command'
permissions:
  'randomevent.command':
    default: 'op'